import PolicyLayout from "@/components/PolicyLayout";

export default function PrivacyPage() {
    return (
        <PolicyLayout
            title="Privacy Policy"
            lastUpdated="May 2026"
            content={
                <>
                    <section>
                        <h2 className="text-xl font-semibold text-white mb-4">1. Introduction</h2>
                        <p>Welcome to Vizhi XR ("we," "our," or "us"). We are committed to protecting your personal information and your right to privacy. This Privacy Policy explains how we collect, use, and safeguard your data when you visit our website and use our spatial computing services, hardware, and applications.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-4">2. Information We Collect</h2>
                        <p>We collect information that you provide directly to us when you express an interest in obtaining information about us or our products. This may include:</p>
                        <ul className="list-disc pl-5 mt-2 space-y-2">
                            <li><strong>Identity Data:</strong> Name, username, or similar identifier.</li>
                            <li><strong>Contact Data:</strong> Email address, physical address, and telephone numbers.</li>
                            <li><strong>Spatial Data:</strong> Environmental mapping and interaction data processed by our hardware to enable AR features.</li>
                            <li><strong>Technical Data:</strong> IP address, browser type, and device information used to access our services.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-4">3. How We Use Your Information</h2>
                        <p>We use personal information collected via our Services for a variety of business purposes, including:</p>
                        <ul className="list-disc pl-5 mt-2 space-y-2">
                            <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
                            <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
                            <li>To enable spatial features and environmental mapping localized to your hardware.</li>
                            <li>To comply with legal obligations and protect against fraudulent activities.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-4">4. Spatial Data and Privacy</h2>
                        <p>As a spatial computing company, we prioritize the security of your environment. Mapping data generated by Vizhi XR hardware is processed locally whenever possible. We do not store detailed maps of your private spaces on our servers unless explicitly authorized for cloud-based collaboration features, in which case data is end-to-end encrypted.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-4">5. Data Retention and Security</h2>
                        <p>We will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We implement a variety of security measures to maintain the safety of your personal information when you enter, submit, or access your personal information.</p>
                    </section>
                </>
            }
        />
    );
}
